
(language-syntax-highlighting a 
(:keywords (a b c) 
:builtin-face (builtin) 
:comment-delimiter-face(delimiter) 
:comment-face (comm) 
:constant-face (const) 
:doc-face (doc) 
:function-name-face (funtion-name) 
:negation-char-face (negation) 
:prepocessor-face (prepo) 
:regexp-grouping-backslash (reg1) 
:regexp-grouping-construct (construct) 
:string-face (string) 
:variable-name-face (variable-name) 
:warning-face (string) 
:variable-name-face (variable-name) 
:type-face (defclass) 
:warning-face (warning)))
